---
language: python
python:
  - "2.7"
  - "3.6"

services: docker

branches:
  only:
    - master

env:
  global:
    - ROLE_NAME=amazon-inspector-agent
  matrix:
    #- ANSIBLE_VERSION=">=2.8,<2.9"
    - ANSIBLE_VERSION=">=2.7,<2.8"
    - ANSIBLE_VERSION=">=2.6,<2.7"
    - ANSIBLE_VERSION=">=2.5,<2.6"

install:
  - pip install ansible"${ANSIBLE_VERSION}"
  - pip install molecule
  - pip install docker

before_script:
  - ls -la
  - cd ../
  - ls -la
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule --version
  - ansible --version
  - molecule lint
  - molecule syntax

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
