---
# references
# https://docs.aws.amazon.com/inspector/latest/userguide/inspector_installing-uninstalling-agents.html

- name: Get amazon linux version from "uname" command
  shell: >
    awk -v FS="recipe_name=" 'NF>1{print $2}' /etc/image-id | tr -d '"' | awk '{print $1}'
  ignore_errors: true
  register: amazon_linux_recipe_name_result
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon'
  changed_when: false

# Define facts to manage amazon linux version in a easy way
- name: Set fact "amazon_linux_distribution_version" for amazon linux 1
  set_fact:
    amazon_linux_distribution_version: 1
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon' and
    amazon_linux_recipe_name_result.stdout == 'amzn'

- name: Set fact "amazon_linux_distribution_version" for amazon linux 2
  set_fact:
    amazon_linux_distribution_version: 2
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon' and
    amazon_linux_recipe_name_result.stdout == 'amzn2'

# Selective include of vars
- name: Include variables for RHEL/Centos
  include_vars: "{{ item }}"
  with_first_found:
    - "redhat.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS' or
      ansible_distribution == 'RedHat'
    )
    and (
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )
  tags:
    - include-redhat-vars

- name: include variables for Amazon Linux
  include_vars: "{{ item }}"
  with_first_found:
    - "amazon.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon'
  tags:
    - include-amazon-vars

- name: Include variables for Debian
  include_vars: "{{ item }}"
  with_first_found:
    - "debian-{{ ansible_distribution_major_version }}.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Debian' and (
      ansible_distribution_major_version == '8' or
      ansible_distribution_major_version == '9'
    )
  tags:
    - include-debian-vars

- name: Include variables for Ubuntu
  include_vars: "{{ item }}"
  with_first_found:
    - "ubuntu-{{ ansible_distribution_major_version }}.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Ubuntu' and (
      ansible_distribution_major_version == '14' or
      ansible_distribution_major_version == '16' or
      ansible_distribution_major_version == '18'
    )
  tags:
    - include-ubuntu-vars

# Installation tasks
- name: Include tasks for installation on RedHat/CentOS/Amazon Linux distribution
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS' or
      ansible_distribution == 'RedHat' or
      ansible_distribution == 'Amazon'
    )
  tags:
    - include-redhat-task

- name: Include tasks for installation on Debian/Ubuntu distribution
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'Debian' and (
      ansible_distribution == 'Debian' or
      ansible_distribution == 'Ubuntu'
    )
  tags:
    - include-debian-task
# # Configure tasks
# - name: Include tasks for configure {{ ssm_package }} on RedHat/CentOS
#   include_tasks: "configure-{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
#   when: >
#     ansible_os_family == 'RedHat' and (
#       ansible_distribution == 'CentOS' or
#       ansible_distribution == 'RedHat'
#     )
#   tags:
#     - include-configure-redhat

# - name: Include tasks for configure {{ ssm_package }} on Amazon Linux distribution
#   include_tasks: "configure-{{ ansible_distribution|lower }}-{{ amazon_linux_distribution_version }}.yml"
#   when: >
#     ansible_os_family == 'RedHat' and (
#       ansible_distribution == 'Amazon'
#     )
#   tags:
#     - include-configure-amzn

# - name: Include tasks for configure {{ ssm_package }} on Debian distribution
#   include_tasks: "configure-{{ ansible_distribution|lower }}.yml"
#   when: >
#     ansible_os_family == 'Debian' and
#     ansible_distribution == 'Debian'
#   tags:
#     - include-configure-debian

# - name: Include tasks for configure {{ ssm_package }} on Ubuntu distribution
#   include_tasks: "configure-{{ ansible_distribution|lower }}.yml"
#   when: >
#     ansible_os_family == 'Debian' and
#     ansible_distribution == 'Ubuntu'
#   tags:
#     - include-configure-ubuntu
